export const FETCH_LANDS = "FETCH_LANDS";
export const FETCH_LAND = "FETCH_LAND";
export const CREATE_LAND = "CREATE_LAND";
export const EDIT_LAND = "EDIT_LAND";

export const FETCH_COMPANIES = "FETCH_COMPANIES";
export const CREATE_COMPANY = "CREATE_COMPANY";
export const FETCH_COMPANY = "FETCH_COMPANY";
export const EDIT_COMPANY = "EDIT_COMPANY";

export const FETCH_PARTNERS = "FETCH_PARTNERS";
export const FETCH_PARTNER = "FETCH_PARTNER";
export const CREATE_PARTNER = "CREATE_PARTNER";
export const EDIT_PARTNER = "EDIT_PARTNER";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const FETCH_COMPANY_PARTNERS = "FETCH_COMPANY_PARTNERS";

export const FETCH_SHARES = "FETCH_SHARES";
export const CREATE_SHARE = "CREATE_SHARE";
export const EDIT_SHARE = "EDIT_SHARE";
export const FETCH_SHARE = "FETCH_SHARE";
export const DELETE_SHARE = "FETCH_SHARE";